<?php

/**
 * @file
 * Contains real_favicon.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\real_favicon\Entity\RealFavicon;

/**
 * Implements hook_help().
 */
function real_favicon_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the real_favicon module.
    case 'help.page.real_favicon':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Add responsive favicons to your site based on the code from http://realfavicongenerator.neet') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_page_attachments_alter().
 */
function real_favicon_page_attachments_alter(array &$attachments) {
  $active_theme = \Drupal::theme()->getActiveTheme()->getName();
  $favicon_themes = \Drupal::config('real_favicon.settings')->get('themes');

  if (isset($favicon_themes[$active_theme])) {
    $real_favicon = RealFavicon::load($favicon_themes[$active_theme]);
    if (!$real_favicon) {
      return;
    }
    $tags = $real_favicon->getValidTagsAsString();
    // Remove default favicon from html_head_link.
    if (!empty($attachments['#attached']['html_head_link'])) {
      foreach ($attachments['#attached']['html_head_link'] as $i => $item) {
        if (!empty($item) && is_array($item)) {
          foreach ($item as $ii => $iitem) {
            if (isset($iitem['rel']) && $iitem['rel'] == 'shortcut icon') {
              unset($attachments['#attached']['html_head_link'][$i][$ii]);
            }
          }
          if (empty($attachments['#attached']['html_head_link'][$i])) {
            unset($attachments['#attached']['html_head_link'][$i]);
          }
        }
      }
      if (empty($attachments['#attached']['html_head_link'])) {
        unset($attachments['#attached']['html_head_link']);
      }
    }
    // Attach favicon tags.
    $attachments['#attached']['html_head'][] = [
      [
        '#type' => 'markup',
        '#markup' => $tags,
        '#allowed_tags' => ['link', 'meta']
      ],
      'real_favicon'
    ];
  }
}
