real_favicon.real_favicon.*:
  type: config_entity
  label: 'Favicon config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    tags:
      type: sequence
      label: 'Tags'
    archive:
      type: sequence
      label: 'Archive'
